[package]
name = "fx_app"
version = "0.1.0"
authors = ["Ilia Yastrebov <iyastreb@cisco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
